### ISSUE TITLE
The bot won't send messages

### ISSUE THREAD

**Issue by ashklootwyk** [Guusvanmeerveld/Tempo#2]
When I start the bot it says on the status to do /help but that doesn't work and neither does @(bot) help. It's the same for all the commands.

**Comment by Guusvanmeerveld** [comment]
Thank you for opening this issue, however, I can not help you with this problem without requiring more information about your bot setup.
If you could please provide a list of information with details about your OS, whether you are using Docker, and runtime logs of the bot.

**Comment by Guusvanmeerveld** [comment]
Closed due to inactivity
